const SkillsData = [
  {
    id: 'angular',
    title: 'Angular',
    logoLight: '/assets/skills/angular.svg',
    logoDark: '/assets/skills/angular.svg',
    description: {
      es: 'Framework de Google para construir aplicaciones SPA escalables, con inyección de dependencias y tipado estricto en TypeScript.',
      en: 'Google framework for building scalable SPA applications, with dependency injection and strict typing in TypeScript.',
    },
    url: 'https://angular.io',
  },
  {
    id: 'react',
    title: 'React & React Native',
    logoLight: '/assets/skills/React_light.svg',
    logoDark: '/assets/skills/React_dark.svg',
    description: {
      es: 'Biblioteca de Facebook basada en componentes para desarrollar interfaces declarativas y reutilizables con Virtual DOM.',
      en: 'Facebook library based on components for developing declarative and reusable interfaces with Virtual DOM.',
    },
    url: 'https://reactjs.org',
  },
  {
    id: 'dotnet-core',
    title: '.NET Core',
    logoLight: '/assets/skills/visual-studio.svg',
    logoDark: '/assets/skills/visual-studio.svg',
    description: {
      es: 'Framework multiplataforma de Microsoft para construir aplicaciones backend robustas y servicios web con C# y ASP.NET.',
      en: 'Microsoft cross-platform framework for building robust backend applications and web services with C# and ASP.NET.',
    },
    url: 'https://docs.microsoft.com/dotnet/core',
  },
  {
    id: 'python',
    title: 'Python',
    logoLight: '/assets/skills/python.svg',
    logoDark: '/assets/skills/python.svg',
    description: {
      es: 'Lenguaje de propósito general, muy legible, usado tanto en scripting como en data science y backend con Django o FastAPI.',
      en: 'General-purpose language, very readable, used in both scripting and data science, as well as backend development with Django or FastAPI.',
    },
    url: 'https://www.python.org',
  },
  {
    id: 'sql-server',
    title: 'Microsoft SQL Server',
    logoLight: '/assets/skills/sql-server.svg',
    logoDark: '/assets/skills/sql-server.svg',
    description: {
      es: 'Sistema gestor de bases de datos relacionales con T-SQL, optimizado para transacciones empresariales.',
      en: 'Relational database management system with T-SQL, optimized for enterprise transactions.',
    },
    url: 'https://docs.microsoft.com/sql/sql-server',
  },
  {
    id: 'mongodb',
    title: 'MongoDB',
    logoLight: '/assets/skills/mongodb.svg',
    logoDark: '/assets/skills/mongodb.svg',
    description: {
      es: 'Base de datos NoSQL orientada a documentos, que facilita la gestión de grandes volúmenes de datos semi-estructurados.',
      en: 'Document-oriented NoSQL database that makes it easy to manage large volumes of semi-structured data.',
    },
    url: 'https://www.mongodb.com',
  },
  {
    id: 'figma',
    title: 'Figma',
    logoLight: '/assets/skills/figma.svg',
    logoDark: '/assets/skills/figma.svg',
    description: {
      es: 'Herramienta colaborativa de diseño UI/UX basada en la nube, perfecta para prototipado y hand-off con desarrolladores.',
      en: 'Collaborative cloud-based UI/UX design tool, perfect for prototyping and hand-off with developers.',
    },
    url: 'https://www.figma.com',
  },
  {
    id: 'powerbi',
    title: 'Power BI',
    logoLight: '/assets/skills/power-bi.svg',
    logoDark: '/assets/skills/power-bi.svg',
    description: {
      es: 'Servicio de Microsoft para análisis de datos y creación de dashboards interactivos sin necesidad de codificar.',
      en: 'Microsoft service for data analysis and creation of interactive dashboards without the need for coding.',
    },
    url: 'https://powerbi.microsoft.com',
  },
  {
    id: 'github',
    title: 'GitHub',
    logoLight: '/assets/skills/GitHub_light.svg',
    logoDark: '/assets/skills/GitHub_dark.svg',
    description: {
      es: 'Plataforma de desarrollo colaborativo que utiliza Git para el control de versiones y la gestión de proyectos.',
      en: 'Collaborative development platform that uses Git for version control and project management.',
    },
    url: 'https://github.com',
  },
  {
    id: 'azure-devops',
    title: 'Azure DevOps',
    logoLight: '/assets/skills/azure-devops.svg',
    logoDark: '/assets/skills/azure-devops.svg',
    description: {
      es: 'Conjunto de servicios en la nube para CI/CD, repositorios Git, gestión de proyectos y pipelines automatizados.',
      en: 'Cloud service suite for CI/CD, Git repositories, project management, and automated pipelines.',
    },
    url: 'https://azure.microsoft.com/services/devops',
  },
];

const OtherTechnologiesData = [
  {
    id: 'html5',
    title: 'HTML5',
    logoLight: '/assets/skills/html5.svg',
    logoDark: '/assets/skills/html5.svg',
    url: 'https://developer.mozilla.org/docs/Web/HTML',
  },
  {
    id: 'css3',
    title: 'CSS3',
    logoLight: '/assets/skills/css_old.svg',
    logoDark: '/assets/skills/css_old.svg',
    url: 'https://developer.mozilla.org/docs/Web/CSS',
  },
  {
    id: 'javascript',
    title: 'JavaScript',
    logoLight: '/assets/skills/javascript.svg',
    logoDark: '/assets/skills/javascript.svg',
    url: 'https://developer.mozilla.org/docs/Web/JavaScript',
  },
  {
    id: 'typescript',
    title: 'TypeScript',
    logoLight: '/assets/skills/typescript.svg',
    logoDark: '/assets/skills/typescript.svg',
    url: 'https://www.typescriptlang.org/',
  },
  {
    id: 'csharp',
    title: 'C#',
    logoLight: '/assets/skills/csharp.svg',
    logoDark: '/assets/skills/csharp.svg',
    url: 'https://learn.microsoft.com/dotnet/csharp/',
  },
  {
    id: 'java',
    title: 'Java',
    logoLight: '/assets/skills/java.svg',
    logoDark: '/assets/skills/java.svg',
    url: 'https://www.java.com/en/',
  },
  {
    id: 'nodejs',
    title: 'Node.js',
    logoLight: '/assets/skills/nodejs.svg',
    logoDark: '/assets/skills/nodejs.svg',
    url: 'https://nodejs.org/',
  },
  {
    id: 'expressjs',
    title: 'Express.js',
    logoLight: '/assets/skills/Express.js_light.svg',
    logoDark: '/assets/skills/Express.js_dark.svg',
    url: 'https://expressjs.com/',
  },
  {
    id: 'tailwindcss',
    title: 'Tailwind CSS',
    logoLight: '/assets/skills/tailwindcss.svg',
    logoDark: '/assets/skills/tailwindcss.svg',
    url: 'https://tailwindcss.com/',
  },
  {
    id: 'git',
    title: 'Git',
    logoLight: '/assets/skills/git.svg',
    logoDark: '/assets/skills/git.svg',
    url: 'https://git-scm.com/',
  },
  {
    id: 'postman',
    title: 'Postman',
    logoLight: '/assets/skills/postman.svg',
    logoDark: '/assets/skills/postman.svg',
    url: 'https://www.postman.com/',
  },
  {
    id: 'npm',
    title: 'npm',
    logoLight: '/assets/skills/npm.svg',
    logoDark: '/assets/skills/npm.svg',
    url: 'https://www.npmjs.com/',
  },
  {
    id: 'notion',
    title: 'Notion',
    logoLight: '/assets/skills/notion.svg',
    logoDark: '/assets/skills/notion.svg',
    url: 'https://www.notion.so/',
  },
  {
    id: 'vscode',
    title: 'Visual Studio Code',
    logoLight: '/assets/skills/vscode.svg',
    logoDark: '/assets/skills/vscode.svg',
    url: 'https://code.visualstudio.com/',
  },
  {
    id: 'visual-studio',
    title: 'Visual Studio',
    logoLight: '/assets/skills/visual-studio.svg',
    logoDark: '/assets/skills/visual-studio.svg',
    url: 'https://visualstudio.microsoft.com/',
  },
  {
    id: 'netlify',
    title: 'Netlify',
    logoLight: '/assets/skills/netlify.svg',
    logoDark: '/assets/skills/netlify.svg',
    url: 'https://www.netlify.com/',
  },
  {
    id: 'jwt',
    title: 'JSON Web Tokens (JWT)',
    logoLight: '/assets/skills/jwt.svg',
    logoDark: '/assets/skills/jwt.svg',
    url: 'https://jwt.io/',
  },
  {
    id: 'canva',
    title: 'Canva',
    logoLight: '/assets/skills/canva.svg',
    logoDark: '/assets/skills/canva.svg',
    url: 'https://www.canva.com/',
  },
  {
    id: 'google-colab',
    title: 'Google Colaboratory',
    logoLight: '/assets/skills/Google_Colaboratory.svg',
    logoDark: '/assets/skills/Google_Colaboratory.svg',
    url: 'https://colab.research.google.com/',
  },
];

export { SkillsData, OtherTechnologiesData };